"""Version and package identifiers for the public exchange contract."""

LEGACY_TASK_SCHEMA_VERSION = "2.0"
CURRENT_TASK_SCHEMA_VERSION = "3.0"
SUPPORTED_TASK_SCHEMA_VERSIONS = frozenset(
    {LEGACY_TASK_SCHEMA_VERSION, CURRENT_TASK_SCHEMA_VERSION}
)

RESULT_SCHEMA_VERSION = "2.2"
SUPPORTED_RESULT_SCHEMA_VERSIONS = (
    "2.0",
    "2.1",
    RESULT_SCHEMA_VERSION,
)

SURVEY_TASK_PACKAGE_KIND = "survey_task"
SURVEY_TASK_EXTENSION = ".ydtask"
SURVEY_RESULT_PACKAGE_KIND = "survey_result"
SURVEY_RESULT_EXTENSION = ".ydresult"
