from shared.forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from shared.forms.engineering.extension_models import (
    OriginalFormCellBinding,
    OriginalFormConclusionBinding,
    OriginalFormEvaluationBinding,
    OriginalFormExportDefinition,
    OriginalFormPrintSettings,
    ValueBindingDefinition,
)

from shared.forms.engineering.formatters import (
    format_stake_range_compact,
)

from shared.evaluation.canal_under_culvert_evaluation import (
    CANAL_UNDER_CULVERT_EVALUATION_ITEMS,
)

FORM_2_8 = EngineeringFormDefinition(
    form_code="form_2_8",
    form_number="2.8",
    form_name="渠下涵工程状况调查表",
    asset_type="canal_under_culvert",
    business_type_code="08",
    asset_name_field="asset_name",
    position=PositionDefinition.range(
                 start_stake_field="start_stake",
                 start_stake_value_key="start_stake_value",
                 end_stake_field="end_stake",
                 end_stake_value_key="end_stake_value",
             ),
    fields=(
        FieldDefinition(
            key="asset_name",
            label="名称",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="start_stake",
            label="起始桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="end_stake",
            label="终止桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+360",
        ),
        FieldDefinition(
            key="design_flow",
            label="设计流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="structure_grade",
            label="建筑物等级",
            input_type="structure_grade",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="build_date",
            label="建成年月",
            input_type="month",
            required=True,
            placeholder="例如：201006",
        ),
        FieldDefinition(
            key="renovation_date",
            label="加固改造年月",
            input_type="month",
            required=False,
            placeholder="例如：202109，可留空",
        ),
        FieldDefinition(
            key="length",
            label="长度",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="increased_flow",
            label="加大流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="structure_form",
            label="结构形式",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="main_structure_material",
            label="主构建筑材料",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="wall_thickness",
            label="壁厚度",
            input_type="decimal",
            required=True,
        ),
        FieldDefinition(
            key="waterstop_form",
            label="止水形式",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="section_size",
            label="尺寸",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
    ),
    sections=(
        FormSectionDefinition(
            title="二、工程基本信息",
            rows=(
                FieldRowDefinition(('asset_name',)),
                FieldRowDefinition(("start_stake",)),
                FieldRowDefinition(("end_stake",)),
                FieldRowDefinition(('design_flow',)),
                FieldRowDefinition(('structure_grade',)),
                FieldRowDefinition(('build_date',)),
                FieldRowDefinition(('renovation_date',)),
                FieldRowDefinition(('length',)),
                FieldRowDefinition(('increased_flow',)),
            ),
        ),
        FormSectionDefinition(
            title="三、结构参数",
            rows=(
                FieldRowDefinition(('structure_form',)),
                FieldRowDefinition(('main_structure_material',)),
                FieldRowDefinition(('wall_thickness',)),
                FieldRowDefinition(('waterstop_form',)),
                FieldRowDefinition(('section_size',)),
            ),
        ),
    ),
    original_form_export_definition=OriginalFormExportDefinition(
        template_filename='form_2_8_V1.xlsx',
        sheet_name='附表2.8',
        field_bindings=(
            OriginalFormCellBinding(
                cell='B5',
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            OriginalFormCellBinding(
                cell='H5',
                binding=ValueBindingDefinition.composite(
                            source="record_data",
                            keys=("start_stake", "end_stake"),
                            formatter=format_stake_range_compact,
                        ),
            ),
            OriginalFormCellBinding(
                cell='J5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            OriginalFormCellBinding(
                cell='D6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='F6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='H6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='length',
                ),
            ),
            OriginalFormCellBinding(
                cell='J6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='increased_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_form',
                ),
            ),
            OriginalFormCellBinding(
                cell='D7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='main_structure_material',
                ),
            ),
            OriginalFormCellBinding(
                cell='F7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='wall_thickness',
                ),
            ),
            OriginalFormCellBinding(
                cell='H7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='waterstop_form',
                ),
            ),
            OriginalFormCellBinding(
                cell='J7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='section_size',
                ),
            ),
        ),
        evaluation_binding=OriginalFormEvaluationBinding(
            column="E",
            start_row=9,
        ),
        conclusion_binding=OriginalFormConclusionBinding(
            survey_comment_cell='C16',
            overall_grade_cell='J16',
            surveyor_signatures_cell='B17',
            water_office_manager_signature_cell='D17',
            engineering_section_chief_signature_cell='F17',
            department_head_signature_cell='H17',
            survey_date_cell='J17',
        ),
        print_settings=OriginalFormPrintSettings(
            print_area='A1:J19',
        ),
        output_filename_prefix='附表2.8_渠下涵工程状况调查表',
        fallback_asset_name='渠下涵',
    ),
    evaluation_items=tuple(
        CANAL_UNDER_CULVERT_EVALUATION_ITEMS
    ),
    grade_options=(
        "A",
        "B",
        "C",
        "D",
    ),
    evaluation_title="四、分项评价",
    conclusion_title="五、调查结论",
)
