from dataclasses import fields

from forms.engineering.models import EngineeringFormDefinition

from shared.forms.engineering.form_2_5 import FORM_2_5 as CORE_DEFINITION

from forms.engineering.extension_models import (
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.formatters import (
    format_dimension_pair_asterisk,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

FORM_2_5 = EngineeringFormDefinition(
    **{field.name: getattr(CORE_DEFINITION, field.name) for field in fields(CORE_DEFINITION)},
    list_definition=build_standard_engineering_list_definition(
            new_button_text='新增隧洞调查',
        ),
    summary_export_definition=SummaryExportDefinition(
        sheet_name="隧洞调查汇总",
        columns=(
            SummaryColumnDefinition(
                header="业务编号",
                width=22,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="business_code",
                ),
            ),
            SummaryColumnDefinition(
                header="名称",
                width=20,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="asset_name",
                ),
            ),
            SummaryColumnDefinition(
                header="基层处",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="department_name",
                ),
            ),
            SummaryColumnDefinition(
                header="水管所",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="office_name",
                ),
            ),
            SummaryColumnDefinition(
                header="渠系",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="canal_name",
                ),
            ),
            SummaryColumnDefinition(
                header="起始桩号",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="start_stake_text",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="终止桩号",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="end_stake_text",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="设计流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="design_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建筑物等级",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_grade",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建成年月",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="build_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加固改造年月",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="renovation_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="长度",
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="length",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加大流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="increased_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="衬砌形式",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="lining_form",
                ),
            ),
            SummaryColumnDefinition(
                header="衬砌厚度",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="lining_thickness",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="混凝土强度",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="concrete_strength",
                ),
            ),
            SummaryColumnDefinition(
                header="进出口底部高程",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="inlet_outlet_bottom_elevation",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="纵坡（n/1000）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="longitudinal_slope",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="断面型式",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="section_form",
                ),
            ),
            SummaryColumnDefinition(
                header="尺寸（宽*高）",
                width=18,
                binding=ValueBindingDefinition.composite(
                    source="record_data",
                    keys=(
                        "section_width",
                        "section_height",
                    ),
                    formatter=format_dimension_pair_asterisk,
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="钢筋保护层厚度",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="cover_thickness",
                ),
                alignment="center",
            ),
        ),
    ),
)
