from dataclasses import fields

from forms.engineering.models import EngineeringFormDefinition

from shared.forms.engineering.form_2_1 import FORM_2_1 as CORE_DEFINITION

from forms.engineering.extension_models import (
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

FORM_2_1 = EngineeringFormDefinition(
    **{field.name: getattr(CORE_DEFINITION, field.name) for field in fields(CORE_DEFINITION)},
    list_definition=build_standard_engineering_list_definition(
            new_button_text='新增渠道渠段调查',
        ),
    summary_export_definition=SummaryExportDefinition(
        sheet_name="渠道渠段调查汇总",
        columns=(
            SummaryColumnDefinition(
                header="业务编号",
                width=22,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="business_code",
                ),
            ),
            SummaryColumnDefinition(
                header="渠道名称",
                width=20,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="asset_name",
                ),
            ),
            SummaryColumnDefinition(
                header="基层处",
                width=15,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="department_name",
                ),
            ),
            SummaryColumnDefinition(
                header="水管所",
                width=15,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="office_name",
                ),
            ),
            SummaryColumnDefinition(
                header="渠系",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="canal_name",
                ),
            ),
            SummaryColumnDefinition(
                header="起始桩号",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="start_stake_text",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="终止桩号",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="end_stake_text",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠段长度（m）",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="section_length",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建成时间",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="build_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加固改造时间",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="renovation_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="纵比降",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="longitudinal_slope",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="设计流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="design_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠道等级",
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_grade",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠道断面形式",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="cross_section_form",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="堤顶宽度（m）",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="embankment_top_width",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠道边坡（内）",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="inner_slope",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠道边坡（外）",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="outer_slope",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加大流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="increased_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠床土质",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="bed_soil",
                ),
            ),
            SummaryColumnDefinition(
                header="防渗衬砌结构",
                width=22,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="lining_structure",
                ),
            ),
            SummaryColumnDefinition(
                header="安全超高（m）",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="freeboard",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠底宽度（m）",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="bottom_width",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="输水损失（m³/km）",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="water_conveyance_loss",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="衬砌材料",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="lining_material",
                ),
            ),
            SummaryColumnDefinition(
                header="衬砌厚度（cm）",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="lining_thickness",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="混凝土强度",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="concrete_strength",
                ),
            ),
            SummaryColumnDefinition(
                header="渠深（m）",
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_depth",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠底高程（m）",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_bottom_elevation",
                ),
                alignment="center",
            ),
        ),
        header_height=38,
    ),
)
