from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.extension_models import (
    OriginalFormCellBinding,
    OriginalFormConclusionBinding,
    OriginalFormEvaluationBinding,
    OriginalFormExportDefinition,
    OriginalFormPrintSettings,
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.formatters import (
    format_stake_range_compact,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.standard_section_measurement_evaluation import (
    STANDARD_SECTION_MEASUREMENT_EVALUATION_ITEMS,
)


FORM_2_10 = EngineeringFormDefinition(
    form_code="form_2_10",
    form_number="2.10",
    form_name='标准断面量水设施工程状况调查表',
    asset_type='standard_section_measurement_facility',
    business_type_code='10',
    asset_name_field="asset_name",
    position=PositionDefinition.range(
                 start_stake_field="start_stake",
                 start_stake_value_key="start_stake_value",
                 end_stake_field="end_stake",
                 end_stake_value_key="end_stake_value",
             ),
    fields=(
        FieldDefinition(
            key='asset_name',
            label='名称',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="start_stake",
            label="起始桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="end_stake",
            label="终止桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+360",
        ),
        FieldDefinition(
            key='design_flow',
            label='设计流量',
            input_type='decimal',
            required=True,
            unit='m³/s',
        ),
        FieldDefinition(
            key='structure_grade',
            label='建筑物等级',
            input_type="structure_grade",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='build_date',
            label='建成年月',
            input_type='month',
            required=True,
            placeholder="例如：201006",
        ),
        FieldDefinition(
            key='renovation_date',
            label='加固改造年月',
            input_type='month',
            required=False,
            placeholder="例如：202109，可留空",
        ),
        FieldDefinition(
            key='length',
            label='长度',
            input_type='decimal',
            required=True,
            unit='m',
        ),
        FieldDefinition(
            key='increased_flow',
            label='加大流量',
            input_type='decimal',
            required=True,
            unit='m³/s',
        ),
        FieldDefinition(
            key='section_form',
            label='断面形式',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='channel_depth',
            label='渠深',
            input_type='decimal',
            required=True,
            unit='m',
        ),
        FieldDefinition(
            key='bottom_width',
            label='渠底宽',
            input_type='decimal',
            required=True,
            unit='m',
        ),
        FieldDefinition(
            key='top_width',
            label='渠口宽',
            input_type='decimal',
            required=True,
            unit='m',
        ),
        FieldDefinition(
            key='longitudinal_slope',
            label='纵坡',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='measurement_facility_type',
            label='量水设施类型',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='lining_type',
            label='衬砌类型',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='measurement_section_length',
            label='测流段长度',
            input_type='decimal',
            required=True,
            unit='m',
        ),
    ),
    sections=(
        FormSectionDefinition(
            title='二、工程基本信息',
            rows=(
                FieldRowDefinition(('asset_name',)),
                FieldRowDefinition(("start_stake",)),
                FieldRowDefinition(("end_stake",)),
                FieldRowDefinition(('design_flow',)),
                FieldRowDefinition(('structure_grade',)),
                FieldRowDefinition(('build_date',)),
                FieldRowDefinition(('renovation_date',)),
                FieldRowDefinition(('length',)),
                FieldRowDefinition(('increased_flow',)),
            ),
        ),
        FormSectionDefinition(
            title='三、量水设施参数',
            rows=(
                FieldRowDefinition(('section_form',)),
                FieldRowDefinition(('channel_depth',)),
                FieldRowDefinition(('bottom_width',)),
                FieldRowDefinition(('top_width',)),
                FieldRowDefinition(('longitudinal_slope',)),
                FieldRowDefinition(('measurement_facility_type',)),
                FieldRowDefinition(('lining_type',)),
                FieldRowDefinition(('measurement_section_length',)),
            ),
        ),
    ),
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text='新增标准断面量水设施调查',
        )
    ),
    # =========================================================
    # 详细汇总导出
    # =========================================================
    summary_export_definition=SummaryExportDefinition(
        sheet_name='标准断面量水设施调查汇总',
        columns=(
            SummaryColumnDefinition(
                header='业务编号',
                width=22,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='business_code',
                ),
            ),
            SummaryColumnDefinition(
                header='名称',
                width=20,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            SummaryColumnDefinition(
                header='基层处',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='department_name',
                ),
            ),
            SummaryColumnDefinition(
                header='水管所',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='office_name',
                ),
            ),
            SummaryColumnDefinition(
                header='渠系',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='canal_name',
                ),
            ),
            SummaryColumnDefinition(
                header='桩号',
                width=14,
                binding=ValueBindingDefinition.composite(
                            source="record_data",
                            keys=("start_stake", "end_stake"),
                            formatter=format_stake_range_compact,
                        ),
            ),
            SummaryColumnDefinition(
                header='设计流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='design_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='建筑物等级',
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='structure_grade',
                ),
            ),
            SummaryColumnDefinition(
                header='建成年月',
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='build_date',
                ),
            ),
            SummaryColumnDefinition(
                header='加固改造年月',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='renovation_date',
                ),
            ),
            SummaryColumnDefinition(
                header='长度（m）',
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='length',
                ),
            ),
            SummaryColumnDefinition(
                header='加大流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='increased_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='断面形式',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='section_form',
                ),
            ),
            SummaryColumnDefinition(
                header='渠深（m）',
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='channel_depth',
                ),
            ),
            SummaryColumnDefinition(
                header='渠底宽（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='bottom_width',
                ),
            ),
            SummaryColumnDefinition(
                header='渠口宽（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='top_width',
                ),
            ),
            SummaryColumnDefinition(
                header='纵坡',
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='longitudinal_slope',
                ),
            ),
            SummaryColumnDefinition(
                header='量水设施类型',
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='measurement_facility_type',
                ),
            ),
            SummaryColumnDefinition(
                header='衬砌类型',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='lining_type',
                ),
            ),
            SummaryColumnDefinition(
                header='测流段长度（m）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='measurement_section_length',
                ),
            ),
        ),
    ),
    # =========================================================
    # 正式原表导出
    # =========================================================
    original_form_export_definition=OriginalFormExportDefinition(
        template_filename='form_2_10_V1.xlsx',
        sheet_name='附表2.10',
        field_bindings=(
            OriginalFormCellBinding(
                cell='B5',
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            OriginalFormCellBinding(
                cell='H5',
                binding=ValueBindingDefinition.composite(
                            source="record_data",
                            keys=("start_stake", "end_stake"),
                            formatter=format_stake_range_compact,
                        ),
            ),
            OriginalFormCellBinding(
                cell='J5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            OriginalFormCellBinding(
                cell='D6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='F6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='H6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='length',
                ),
            ),
            OriginalFormCellBinding(
                cell='J6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='increased_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='section_form',
                ),
            ),
            OriginalFormCellBinding(
                cell='D7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='channel_depth',
                ),
            ),
            OriginalFormCellBinding(
                cell='F7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='bottom_width',
                ),
            ),
            OriginalFormCellBinding(
                cell='H7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='top_width',
                ),
            ),
            OriginalFormCellBinding(
                cell='B8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='longitudinal_slope',
                ),
            ),
            OriginalFormCellBinding(
                cell='D8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='measurement_facility_type',
                ),
            ),
            OriginalFormCellBinding(
                cell='F8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='lining_type',
                ),
            ),
            OriginalFormCellBinding(
                cell='H8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='measurement_section_length',
                ),
            ),
        ),
        evaluation_binding=OriginalFormEvaluationBinding(
            column="E",
            start_row=10,
        ),
        conclusion_binding=OriginalFormConclusionBinding(
            survey_comment_cell='C22',
            overall_grade_cell='J22',
            surveyor_signatures_cell='B23',
            water_office_manager_signature_cell='D23',
            engineering_section_chief_signature_cell='F23',
            department_head_signature_cell='H23',
            survey_date_cell='J23',
        ),
        print_settings=OriginalFormPrintSettings(
            print_area='A1:J24',
        ),
        output_filename_prefix='附表2.10_标准断面量水设施工程状况调查表',
        fallback_asset_name='标准断面量水设施',
    ),
    evaluation_items=tuple(
        STANDARD_SECTION_MEASUREMENT_EVALUATION_ITEMS
    ),
    grade_options=(
        "A",
        "B",
        "C",
    ),
    evaluation_title="四、分项评价",
    conclusion_title="五、调查结论",
)
