from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.extension_models import (
    OriginalFormCellBinding,
    OriginalFormConclusionBinding,
    OriginalFormEvaluationBinding,
    OriginalFormExportDefinition,
    OriginalFormPrintSettings,
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.culvert_evaluation import (
    CULVERT_EVALUATION_ITEMS,
)

FORM_2_6 = EngineeringFormDefinition(
    # =========================================================
    # 表单身份
    # =========================================================
    form_code="form_2_6",
    form_number="2.6",
    form_name=("涵洞（暗涵）工程状况调查表"),
    asset_type="culvert",
    business_type_code="06",
    asset_name_field="asset_name",
    # =========================================================
    # 工程位置
    # =========================================================
    position=PositionDefinition.point(
        stake_field="stake",
        stake_value_key="stake_value",
    ),
    # =========================================================
    # 字段
    # =========================================================
    fields=(
        # -----------------------------------------------------
        # 二、工程基本信息
        # -----------------------------------------------------
        FieldDefinition(
            key="asset_name",
            label="名称",
            input_type="text",
            required=True,
            placeholder=("填写涵洞（暗涵）名称"),
        ),
        FieldDefinition(
            key="stake",
            label="桩号",
            input_type="stake",
            required=True,
            placeholder=("例如：CH12+350"),
        ),
        FieldDefinition(
            key="design_flow",
            label="设计流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="structure_grade",
            label="建筑物等级",
            input_type="text",
            required=True,
            placeholder=("按原始资料填写"),
        ),
        FieldDefinition(
            key="build_date",
            label="建成年月",
            input_type="month",
            required=True,
        ),
        FieldDefinition(
            key="renovation_date",
            label="加固改造年月",
            input_type="month",
            required=False,
            placeholder=("例如：202109，可留空"),
        ),
        # 正式原表未明确标注单位。
        FieldDefinition(
            key="length",
            label="长度",
            input_type="decimal",
            required=True,
        ),
        FieldDefinition(
            key="increased_flow",
            label="加大流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        # -----------------------------------------------------
        # 三、结构与断面参数
        # -----------------------------------------------------
        FieldDefinition(
            key="structure_form",
            label="结构形式",
            input_type="text",
            required=True,
            placeholder=("按原始资料填写"),
        ),
        FieldDefinition(
            key="main_structure_material",
            label="主构建筑材料",
            input_type="text",
            required=True,
            placeholder=("按原始资料填写"),
        ),
        FieldDefinition(
            key="concrete_strength",
            label="混凝土强度",
            input_type="text",
            required=True,
            placeholder=("例如：C30"),
        ),
        # 正式原表未明确标注单位。
        FieldDefinition(
            key="cover_thickness",
            label="钢筋保护层厚度",
            input_type="decimal",
            required=True,
        ),
        FieldDefinition(
            key="soil_cover_thickness",
            label="覆土厚度",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="channel_width",
            label="渠宽",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="channel_depth",
            label="渠深",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="channel_bottom_elevation",
            label="渠底高程",
            input_type="signed_decimal",
            required=True,
            unit="m",
        ),
    ),
    # =========================================================
    # 页面布局
    # =========================================================
    sections=(
        FormSectionDefinition(
            title="二、工程基本信息",
            rows=(
                FieldRowDefinition(("asset_name",)),
                FieldRowDefinition(("stake",)),
                FieldRowDefinition(("design_flow",)),
                FieldRowDefinition(("structure_grade",)),
                FieldRowDefinition(("build_date",)),
                FieldRowDefinition(("renovation_date",)),
                FieldRowDefinition(("length",)),
                FieldRowDefinition(("increased_flow",)),
            ),
        ),
        FormSectionDefinition(
            title=("三、结构与断面参数"),
            rows=(
                FieldRowDefinition(("structure_form",)),
                FieldRowDefinition(("main_structure_material",)),
                FieldRowDefinition(("concrete_strength",)),
                FieldRowDefinition(("cover_thickness",)),
                FieldRowDefinition(("soil_cover_thickness",)),
                FieldRowDefinition(("channel_width",)),
                FieldRowDefinition(("channel_depth",)),
                FieldRowDefinition(("channel_bottom_elevation",)),
            ),
        ),
    ),
    # =========================================================
    # 当前批次列表
    # =========================================================
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text='新增涵洞（暗涵）调查',
        )
    ),

    # =========================================================
    # 分项评价
    # =========================================================
    # =========================================================
    # 详细汇总导出
    # =========================================================
    summary_export_definition=SummaryExportDefinition(
        sheet_name="涵洞（暗涵）调查汇总",
        columns=(
            SummaryColumnDefinition(
                header="业务编号",
                width=22,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="business_code",
                ),
            ),
            SummaryColumnDefinition(
                header="名称",
                width=20,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="asset_name",
                ),
            ),
            SummaryColumnDefinition(
                header="基层处",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="department_name",
                ),
            ),
            SummaryColumnDefinition(
                header="水管所",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="office_name",
                ),
            ),
            SummaryColumnDefinition(
                header="渠系",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="canal_name",
                ),
            ),
            SummaryColumnDefinition(
                header="桩号",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="stake",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="设计流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="design_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建筑物等级",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_grade",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建成年月",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="build_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加固改造年月",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="renovation_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="长度",
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="length",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加大流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="increased_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="结构形式",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_form",
                ),
            ),
            SummaryColumnDefinition(
                header="主构建筑材料",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="main_structure_material",
                ),
            ),
            SummaryColumnDefinition(
                header="混凝土强度",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="concrete_strength",
                ),
            ),
            SummaryColumnDefinition(
                header="钢筋保护层厚度",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="cover_thickness",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="覆土厚度（m）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="soil_cover_thickness",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠宽（m）",
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_width",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠深（m）",
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_depth",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="渠底高程（m）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_bottom_elevation",
                ),
                alignment="center",
            ),
        ),
    ),
    # =========================================================
    # 正式原表导出
    # =========================================================
    original_form_export_definition=OriginalFormExportDefinition(
        template_filename="form_2_6_V1.xlsx",
        sheet_name="附表2.6",
        field_bindings=(
            OriginalFormCellBinding(
                cell="B5",
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="asset_name",
                ),
            ),
            OriginalFormCellBinding(
                cell="H5",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="stake",
                ),
            ),
            OriginalFormCellBinding(
                cell="J5",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="design_flow",
                ),
            ),
            OriginalFormCellBinding(
                cell="B6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_grade",
                ),
            ),
            OriginalFormCellBinding(
                cell="D6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="build_date",
                ),
            ),
            OriginalFormCellBinding(
                cell="F6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="renovation_date",
                ),
            ),
            OriginalFormCellBinding(
                cell="H6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="length",
                ),
            ),
            OriginalFormCellBinding(
                cell="J6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="increased_flow",
                ),
            ),
            OriginalFormCellBinding(
                cell="B7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_form",
                ),
            ),
            OriginalFormCellBinding(
                cell="D7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="main_structure_material",
                ),
            ),
            OriginalFormCellBinding(
                cell="F7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="concrete_strength",
                ),
            ),
            OriginalFormCellBinding(
                cell="H7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="cover_thickness",
                ),
            ),
            OriginalFormCellBinding(
                cell="J7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="soil_cover_thickness",
                ),
            ),
            OriginalFormCellBinding(
                cell="B8",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_width",
                ),
            ),
            OriginalFormCellBinding(
                cell="D8",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_depth",
                ),
            ),
            OriginalFormCellBinding(
                cell="F8",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_bottom_elevation",
                ),
            ),
        ),
        evaluation_binding=OriginalFormEvaluationBinding(
            column="E",
            start_row=10,
        ),
        conclusion_binding=OriginalFormConclusionBinding(
            survey_comment_cell="C21",
            overall_grade_cell="J21",
            survey_date_cell="J22",
        ),
        print_settings=OriginalFormPrintSettings(
            print_area="A1:J23",
        ),
        output_filename_prefix=(
            "附表2.6_涵洞（暗涵）工程状况调查表"
        ),
        fallback_asset_name="涵洞（暗涵）",
    ),
    evaluation_items=tuple(CULVERT_EVALUATION_ITEMS),
    grade_options=(
        "A",
        "B",
        "C",
        "D",
    ),
    evaluation_title="四、分项评价",
    conclusion_title="五、调查结论",
)
