from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.extension_models import (
    OriginalFormCellBinding,
    OriginalFormConclusionBinding,
    OriginalFormEvaluationBinding,
    OriginalFormExportDefinition,
    OriginalFormPrintSettings,
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.formatters import (
    format_stake_range_compact,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.inverted_siphon_evaluation import (
    INVERTED_SIPHON_EVALUATION_ITEMS,
)

FORM_2_4 = EngineeringFormDefinition(
    form_code="form_2_4",
    form_number="2.4",
    form_name=("倒虹吸工程状况调查表"),
    asset_type="inverted_siphon",
    business_type_code="04",
    asset_name_field="asset_name",
    position=PositionDefinition.range(
                 start_stake_field="start_stake",
                 start_stake_value_key="start_stake_value",
                 end_stake_field="end_stake",
                 end_stake_value_key="end_stake_value",
             ),
    fields=(
        # -----------------------------------------------------
        # 二、工程基本信息
        # -----------------------------------------------------
        FieldDefinition(
            key="asset_name",
            label="名称",
            input_type="text",
            required=True,
            placeholder="填写倒虹吸名称",
        ),
        FieldDefinition(
            key="start_stake",
            label="起始桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="end_stake",
            label="终止桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+360",
        ),
        FieldDefinition(
            key="design_flow",
            label="设计流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="structure_grade",
            label="建筑物等级",
            input_type="structure_grade",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="build_date",
            label="建成年月",
            input_type="month",
            required=True,
        ),
        FieldDefinition(
            key="renovation_date",
            label="加固改造年月",
            input_type="month",
            required=False,
            placeholder=("例如：202109，可留空"),
        ),
        FieldDefinition(
            key="length",
            label="长度",
            input_type="decimal",
            required=True,
        ),
        FieldDefinition(
            key="increased_flow",
            label="加大流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        # -----------------------------------------------------
        # 三、结构参数
        # -----------------------------------------------------
        FieldDefinition(
            key="structure_form",
            label="结构形式",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="section_size",
            label="尺寸",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="pipe_body_structure",
            label="管身结构",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="wall_thickness",
            label="壁厚度",
            input_type="decimal",
            required=True,
        ),
        FieldDefinition(
            key="waterstop_form",
            label="止水形式",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="channel_bottom_elevation",
            label="渠底高程",
            input_type="signed_decimal",
            required=True,
        ),
    ),
    sections=(
        FormSectionDefinition(
            title="二、工程基本信息",
            rows=(
                FieldRowDefinition(("asset_name",)),
                FieldRowDefinition(("start_stake",)),
                FieldRowDefinition(("end_stake",)),
                FieldRowDefinition(("design_flow",)),
                FieldRowDefinition(("structure_grade",)),
                FieldRowDefinition(("build_date",)),
                FieldRowDefinition(("renovation_date",)),
                FieldRowDefinition(("length",)),
                FieldRowDefinition(("increased_flow",)),
            ),
        ),
        FormSectionDefinition(
            title="三、结构参数",
            rows=(
                FieldRowDefinition(("structure_form",)),
                FieldRowDefinition(("section_size",)),
                FieldRowDefinition(("pipe_body_structure",)),
                FieldRowDefinition(("wall_thickness",)),
                FieldRowDefinition(("waterstop_form",)),
                FieldRowDefinition(("channel_bottom_elevation",)),
            ),
        ),
    ),
    # =========================================================
    # 当前批次列表
    # =========================================================
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text='新增倒虹吸调查',
        )
    ),
    # =========================================================
    # 详细汇总导出
    # =========================================================
    summary_export_definition=SummaryExportDefinition(
        sheet_name="倒虹吸调查汇总",
        columns=(
            SummaryColumnDefinition(
                header="业务编号",
                width=22,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="business_code",
                ),
            ),
            SummaryColumnDefinition(
                header="名称",
                width=20,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="asset_name",
                ),
            ),
            SummaryColumnDefinition(
                header="基层处",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="department_name",
                ),
            ),
            SummaryColumnDefinition(
                header="水管所",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="office_name",
                ),
            ),
            SummaryColumnDefinition(
                header="渠系",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="canal_name",
                ),
            ),
            SummaryColumnDefinition(
                header="桩号",
                width=14,
                binding=ValueBindingDefinition.composite(
                            source="record_data",
                            keys=("start_stake", "end_stake"),
                            formatter=format_stake_range_compact,
                        ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="设计流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="design_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建筑物等级",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_grade",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建成年月",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="build_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加固改造年月",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="renovation_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="长度",
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="length",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加大流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="increased_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="结构形式",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_form",
                ),
            ),
            SummaryColumnDefinition(
                header="尺寸",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="section_size",
                ),
            ),
            SummaryColumnDefinition(
                header="管身结构",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="pipe_body_structure",
                ),
            ),
            SummaryColumnDefinition(
                header="壁厚度",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="wall_thickness",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="止水形式",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="waterstop_form",
                ),
            ),
            SummaryColumnDefinition(
                header="渠底高程",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_bottom_elevation",
                ),
                alignment="center",
            ),
        ),
    ),
    # =========================================================
    # 正式原表导出
    # =========================================================
    original_form_export_definition=OriginalFormExportDefinition(
        template_filename="form_2_4_V1.xlsx",
        sheet_name="附表2.4",
        field_bindings=(
            OriginalFormCellBinding(
                cell="B5",
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="asset_name",
                ),
            ),
            OriginalFormCellBinding(
                cell="H5",
                binding=ValueBindingDefinition.composite(
                            source="record_data",
                            keys=("start_stake", "end_stake"),
                            formatter=format_stake_range_compact,
                        ),
            ),
            OriginalFormCellBinding(
                cell="J5",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="design_flow",
                ),
            ),
            OriginalFormCellBinding(
                cell="B6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_grade",
                ),
            ),
            OriginalFormCellBinding(
                cell="D6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="build_date",
                ),
            ),
            OriginalFormCellBinding(
                cell="F6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="renovation_date",
                ),
            ),
            OriginalFormCellBinding(
                cell="H6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="length",
                ),
            ),
            OriginalFormCellBinding(
                cell="J6",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="increased_flow",
                ),
            ),
            OriginalFormCellBinding(
                cell="B7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_form",
                ),
            ),
            OriginalFormCellBinding(
                cell="D7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="section_size",
                ),
            ),
            OriginalFormCellBinding(
                cell="F7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="pipe_body_structure",
                ),
            ),
            OriginalFormCellBinding(
                cell="H7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="wall_thickness",
                ),
            ),
            OriginalFormCellBinding(
                cell="J7",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="waterstop_form",
                ),
            ),
            OriginalFormCellBinding(
                cell="B8",
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_bottom_elevation",
                ),
            ),
        ),
        evaluation_binding=OriginalFormEvaluationBinding(
            column="E",
            start_row=10,
        ),
        conclusion_binding=OriginalFormConclusionBinding(
            survey_comment_cell="C22",
            overall_grade_cell="J22",
            surveyor_signatures_cell="B23",
            water_office_manager_signature_cell="D23",
            engineering_section_chief_signature_cell="F23",
            department_head_signature_cell="H23",
            survey_date_cell="J23",
        ),
        print_settings=OriginalFormPrintSettings(
            print_area="A1:J25",
        ),
        output_filename_prefix=(
            "附表2.4_倒虹吸工程状况调查表"
        ),
        fallback_asset_name="倒虹吸",
    ),
    evaluation_items=tuple(INVERTED_SIPHON_EVALUATION_ITEMS),
    grade_options=(
        "A",
        "B",
        "C",
        "D",
    ),
    evaluation_title=("四、分项评价"),
    conclusion_title=("五、调查结论"),
)
