from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.extension_models import (
    OriginalFormCellBinding,
    OriginalFormConclusionBinding,
    OriginalFormEvaluationBinding,
    OriginalFormExportDefinition,
    OriginalFormPrintSettings,
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.bridge_evaluation import (
    BRIDGE_EVALUATION_ITEMS,
)


FORM_2_12 = EngineeringFormDefinition(
    form_code="form_2_12",
    form_number="2.12",
    form_name="桥梁工程状况调查表",
    asset_type="bridge",
    business_type_code="12",
    asset_name_field="asset_name",
    position=PositionDefinition.point(
        stake_field="stake",
        stake_value_key="stake_value",
    ),
    fields=(
        FieldDefinition(
            key="asset_name",
            label="名称",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="stake",
            label="桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="design_flow",
            label="设计流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="structure_grade",
            label="建筑物等级",
            input_type="structure_grade",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="build_date",
            label="建成年月",
            input_type="month",
            required=True,
            placeholder="例如：201006",
        ),
        FieldDefinition(
            key="renovation_date",
            label="加固改造年月",
            input_type="month",
            required=False,
            placeholder="例如：202109，可留空",
        ),
        FieldDefinition(
            key="width_span",
            label="宽*跨",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="load_capacity",
            label="承载重量",
            input_type="decimal",
            required=True,
            unit="吨",
        ),
        FieldDefinition(
            key="structure_form",
            label="结构形式",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="reinforced_concrete_strength",
            label="钢筋混凝土强度",
            input_type="concrete_strength",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="cover_thickness",
            label="钢筋保护层厚度",
            input_type="decimal",
            required=True,
        ),
    ),
    sections=(
        FormSectionDefinition(
            title="二、工程基本信息",
            rows=(
                FieldRowDefinition(('asset_name',)),
                FieldRowDefinition(('stake',)),
                FieldRowDefinition(('design_flow',)),
                FieldRowDefinition(('structure_grade',)),
                FieldRowDefinition(('build_date',)),
                FieldRowDefinition(('renovation_date',)),
                FieldRowDefinition(('width_span',)),
                FieldRowDefinition(('load_capacity',)),
            ),
        ),
        FormSectionDefinition(
            title="三、结构参数",
            rows=(
                FieldRowDefinition(('structure_form',)),
                FieldRowDefinition(('reinforced_concrete_strength',)),
                FieldRowDefinition(('cover_thickness',)),
            ),
        ),
    ),
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text="新增桥梁调查",
        )
    ),
    # =========================================================
    # 详细汇总导出
    # =========================================================
    summary_export_definition=SummaryExportDefinition(
        sheet_name='桥梁调查汇总',
        columns=(
            SummaryColumnDefinition(
                header='业务编号',
                width=22,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='business_code',
                ),
            ),
            SummaryColumnDefinition(
                header='名称',
                width=20,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            SummaryColumnDefinition(
                header='基层处',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='department_name',
                ),
            ),
            SummaryColumnDefinition(
                header='水管所',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='office_name',
                ),
            ),
            SummaryColumnDefinition(
                header='渠系',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='canal_name',
                ),
            ),
            SummaryColumnDefinition(
                header='桩号',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stake',
                ),
            ),
            SummaryColumnDefinition(
                header='设计流量',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='建筑物等级',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            SummaryColumnDefinition(
                header='建成年月',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            SummaryColumnDefinition(
                header='加固改造年月',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            SummaryColumnDefinition(
                header='宽*跨',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='width_span',
                ),
            ),
            SummaryColumnDefinition(
                header='承载重量（吨）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='load_capacity',
                ),
            ),
            SummaryColumnDefinition(
                header='结构形式',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_form',
                ),
            ),
            SummaryColumnDefinition(
                header='钢筋混凝土强度',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='reinforced_concrete_strength',
                ),
            ),
            SummaryColumnDefinition(
                header='钢筋保护层厚度',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='cover_thickness',
                ),
            ),
        ),
    ),
    # =========================================================
    # 正式原表导出
    # =========================================================
    original_form_export_definition=OriginalFormExportDefinition(
        template_filename='form_2_12_V1.xlsx',
        sheet_name='附表2.12',
        field_bindings=(
            OriginalFormCellBinding(
                cell='B5',
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            OriginalFormCellBinding(
                cell='H5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stake',
                ),
            ),
            OriginalFormCellBinding(
                cell='J5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            OriginalFormCellBinding(
                cell='D6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='F6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='H6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='width_span',
                ),
            ),
            OriginalFormCellBinding(
                cell='J6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='load_capacity',
                ),
            ),
            OriginalFormCellBinding(
                cell='B7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_form',
                ),
            ),
            OriginalFormCellBinding(
                cell='D7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='reinforced_concrete_strength',
                ),
            ),
            OriginalFormCellBinding(
                cell='F7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='cover_thickness',
                ),
            ),
        ),
        evaluation_binding=OriginalFormEvaluationBinding(
            column="E",
            start_row=9,
        ),
        conclusion_binding=OriginalFormConclusionBinding(
            survey_comment_cell='C19',
            overall_grade_cell='J19',
            surveyor_signatures_cell='B20',
            water_office_manager_signature_cell='D20',
            engineering_section_chief_signature_cell='F20',
            department_head_signature_cell='H20',
            survey_date_cell='J20',
        ),
        print_settings=OriginalFormPrintSettings(
            print_area='A1:J21',
        ),
        output_filename_prefix='附表2.12_桥梁工程状况调查表',
        fallback_asset_name='桥梁',
    ),
    evaluation_items=tuple(
        BRIDGE_EVALUATION_ITEMS
    ),
    grade_options=(
        "A",
        "B",
        "C",
        "D",
    ),
    evaluation_title="四、分项评价",
    conclusion_title="五、调查结论",
)
