from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.extension_models import (
    OriginalFormCellBinding,
    OriginalFormConclusionBinding,
    OriginalFormEvaluationBinding,
    OriginalFormExportDefinition,
    OriginalFormPrintSettings,
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.formatters import (
    format_stake_range_spaced,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.drop_steep_slope_evaluation import (
    DROP_STEEP_SLOPE_EVALUATION_ITEMS,
)


FORM_2_7 = EngineeringFormDefinition(
    form_code="form_2_7",
    form_number="2.7",
    form_name="跌水与陡坡工程状况调查表",
    asset_type="drop_steep_slope",
    business_type_code="07",
    asset_name_field="asset_name",
    position=PositionDefinition.range(
        start_stake_field="start_stake",
        start_stake_value_key="start_stake_value",
        end_stake_field="end_stake",
        end_stake_value_key="end_stake_value",
    ),
    fields=(
        FieldDefinition(
            key="asset_name",
            label="名称",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="start_stake",
            label="起始桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="end_stake",
            label="终止桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="design_flow",
            label="设计流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="structure_grade",
            label="建筑物等级",
            input_type="structure_grade",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="build_date",
            label="建成年月",
            input_type="month",
            required=True,
            placeholder="例如：201006",
        ),
        FieldDefinition(
            key="renovation_date",
            label="加固改造年月",
            input_type="month",
            required=False,
            placeholder="例如：202109，可留空",
        ),
        FieldDefinition(
            key="length",
            label="长度",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="increased_flow",
            label="加大流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="drop_height",
            label="跌差",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="drop_tongue_width",
            label="跌舌宽",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="main_structure_material",
            label="主构建筑材料",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="concrete_strength",
            label="混凝土强度",
            input_type="concrete_strength",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="cover_thickness",
            label="钢筋保护层厚度",
            input_type="decimal",
            required=True,
        ),
        FieldDefinition(
            key="stilling_pool_depth",
            label="消力池深",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="stilling_pool_length",
            label="消力池长",
            input_type="decimal",
            required=True,
            unit="m",
        ),
    ),
    sections=(
        FormSectionDefinition(
            title="二、工程基本信息",
            rows=(
                FieldRowDefinition(('asset_name',)),
                FieldRowDefinition(('start_stake',)),
                FieldRowDefinition(('end_stake',)),
                FieldRowDefinition(('design_flow',)),
                FieldRowDefinition(('structure_grade',)),
                FieldRowDefinition(('build_date',)),
                FieldRowDefinition(('renovation_date',)),
                FieldRowDefinition(('length',)),
                FieldRowDefinition(('increased_flow',)),
            ),
        ),
        FormSectionDefinition(
            title="三、结构参数",
            rows=(
                FieldRowDefinition(('drop_height',)),
                FieldRowDefinition(('drop_tongue_width',)),
                FieldRowDefinition(('main_structure_material',)),
                FieldRowDefinition(('concrete_strength',)),
                FieldRowDefinition(('cover_thickness',)),
                FieldRowDefinition(('stilling_pool_depth',)),
                FieldRowDefinition(('stilling_pool_length',)),
            ),
        ),
    ),
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text="新增跌水与陡坡调查",
        )
    ),
    # =========================================================
    # 详细汇总导出
    # =========================================================
    summary_export_definition=SummaryExportDefinition(
        sheet_name='跌水与陡坡调查汇总',
        columns=(
            SummaryColumnDefinition(
                header='业务编号',
                width=22,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='business_code',
                ),
            ),
            SummaryColumnDefinition(
                header='名称',
                width=20,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            SummaryColumnDefinition(
                header='基层处',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='department_name',
                ),
            ),
            SummaryColumnDefinition(
                header='水管所',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='office_name',
                ),
            ),
            SummaryColumnDefinition(
                header='渠系',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='canal_name',
                ),
            ),
            SummaryColumnDefinition(
                header='起始桩号',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='start_stake',
                ),
            ),
            SummaryColumnDefinition(
                header='终止桩号',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='end_stake',
                ),
            ),
            SummaryColumnDefinition(
                header='设计流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='建筑物等级',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            SummaryColumnDefinition(
                header='建成年月',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            SummaryColumnDefinition(
                header='加固改造年月',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            SummaryColumnDefinition(
                header='长度（m）',
                width=12,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='length',
                ),
            ),
            SummaryColumnDefinition(
                header='加大流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='increased_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='跌差（m）',
                width=12,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='drop_height',
                ),
            ),
            SummaryColumnDefinition(
                header='跌舌宽（m）',
                width=12,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='drop_tongue_width',
                ),
            ),
            SummaryColumnDefinition(
                header='主构建筑材料',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='main_structure_material',
                ),
            ),
            SummaryColumnDefinition(
                header='混凝土强度',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='concrete_strength',
                ),
            ),
            SummaryColumnDefinition(
                header='钢筋保护层厚度',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='cover_thickness',
                ),
            ),
            SummaryColumnDefinition(
                header='消力池深（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stilling_pool_depth',
                ),
            ),
            SummaryColumnDefinition(
                header='消力池长（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stilling_pool_length',
                ),
            ),
        ),
    ),
    # =========================================================
    # 正式原表导出
    # =========================================================
    original_form_export_definition=OriginalFormExportDefinition(
        template_filename='form_2_7_V1.xlsx',
        sheet_name='附表2.7',
        field_bindings=(
            OriginalFormCellBinding(
                cell='B5',
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            OriginalFormCellBinding(
                cell='H5',
                binding=ValueBindingDefinition.composite(
                    source='record_data',
                    keys=('start_stake', 'end_stake'),
                    formatter=format_stake_range_spaced,
                ),
            ),
            OriginalFormCellBinding(
                cell='J5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            OriginalFormCellBinding(
                cell='D6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='F6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='H6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='length',
                ),
            ),
            OriginalFormCellBinding(
                cell='J6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='increased_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='drop_height',
                ),
            ),
            OriginalFormCellBinding(
                cell='D7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='drop_tongue_width',
                ),
            ),
            OriginalFormCellBinding(
                cell='F7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='main_structure_material',
                ),
            ),
            OriginalFormCellBinding(
                cell='H7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='concrete_strength',
                ),
            ),
            OriginalFormCellBinding(
                cell='J7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='cover_thickness',
                ),
            ),
            OriginalFormCellBinding(
                cell='B8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stilling_pool_depth',
                ),
            ),
            OriginalFormCellBinding(
                cell='D8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stilling_pool_length',
                ),
            ),
        ),
        evaluation_binding=OriginalFormEvaluationBinding(
            column="E",
            start_row=10,
        ),
        conclusion_binding=OriginalFormConclusionBinding(
            survey_comment_cell='C20',
            overall_grade_cell='J20',
            surveyor_signatures_cell='B21',
            water_office_manager_signature_cell='D21',
            engineering_section_chief_signature_cell='F21',
            department_head_signature_cell='H21',
            survey_date_cell='J21',
        ),
        print_settings=OriginalFormPrintSettings(
            print_area='A1:J22',
        ),
        output_filename_prefix='附表2.7_跌水与陡坡工程状况调查表',
        fallback_asset_name='跌水与陡坡',
    ),
    evaluation_items=tuple(
        DROP_STEEP_SLOPE_EVALUATION_ITEMS
    ),
    grade_options=(
        "A",
        "B",
        "C",
        "D",
    ),
    evaluation_title="四、分项评价",
    conclusion_title="五、调查结论",
)
