from dataclasses import fields

from forms.engineering.models import EngineeringFormDefinition

from shared.forms.engineering.form_2_13 import FORM_2_13 as CORE_DEFINITION

from forms.engineering.extension_models import (
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.formatters import (
    format_stake_range_compact,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

FORM_2_13 = EngineeringFormDefinition(
    **{field.name: getattr(CORE_DEFINITION, field.name) for field in fields(CORE_DEFINITION)},
    list_definition=build_standard_engineering_list_definition(
            new_button_text="新增砌石工程调查",
        ),
    summary_export_definition=SummaryExportDefinition(
        sheet_name='砌石工程调查汇总',
        columns=(
            SummaryColumnDefinition(
                header='业务编号',
                width=22,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='business_code',
                ),
            ),
            SummaryColumnDefinition(
                header='名称',
                width=20,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            SummaryColumnDefinition(
                header='基层处',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='department_name',
                ),
            ),
            SummaryColumnDefinition(
                header='水管所',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='office_name',
                ),
            ),
            SummaryColumnDefinition(
                header='渠系',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='canal_name',
                ),
            ),
            SummaryColumnDefinition(
                header='桩号',
                width=14,
                binding=ValueBindingDefinition.composite(
                            source="record_data",
                            keys=("start_stake", "end_stake"),
                            formatter=format_stake_range_compact,
                        ),
            ),
            SummaryColumnDefinition(
                header='设计流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='纵比降',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='longitudinal_slope',
                ),
            ),
            SummaryColumnDefinition(
                header='建筑物等级',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            SummaryColumnDefinition(
                header='建成年月',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            SummaryColumnDefinition(
                header='加固改造年月',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            SummaryColumnDefinition(
                header='加大流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='increased_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='渠底高程（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='channel_bottom_elevation',
                ),
            ),
            SummaryColumnDefinition(
                header='长度',
                width=12,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='length',
                ),
            ),
            SummaryColumnDefinition(
                header='渠底宽度（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='bottom_width',
                ),
            ),
            SummaryColumnDefinition(
                header='渠深（m）',
                width=12,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='channel_depth',
                ),
            ),
            SummaryColumnDefinition(
                header='渠口宽（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='top_width',
                ),
            ),
            SummaryColumnDefinition(
                header='衬砌厚度（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='lining_thickness',
                ),
            ),
            SummaryColumnDefinition(
                header='断面形式',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='section_form',
                ),
            ),
            SummaryColumnDefinition(
                header='渠床土质',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='bed_soil',
                ),
            ),
            SummaryColumnDefinition(
                header='挖/填方渠道',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='earthwork_type',
                ),
            ),
            SummaryColumnDefinition(
                header='输水损失（m³/km）',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='water_conveyance_loss',
                ),
            ),
        ),
    ),
)
