from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.inverted_siphon_evaluation import (
    INVERTED_SIPHON_EVALUATION_ITEMS,
)

FORM_2_4 = EngineeringFormDefinition(
    form_code="form_2_4",
    form_number="2.4",
    form_name=("倒虹吸工程状况调查表"),
    asset_type="inverted_siphon",
    business_type_code="04",
    asset_name_field="asset_name",
    position=PositionDefinition.point(
        stake_field="stake",
        stake_value_key="stake_value",
    ),
    fields=(
        # -----------------------------------------------------
        # 二、工程基本信息
        # -----------------------------------------------------
        FieldDefinition(
            key="asset_name",
            label="名称",
            input_type="text",
            required=True,
            placeholder="填写倒虹吸名称",
        ),
        FieldDefinition(
            key="stake",
            label="桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="design_flow",
            label="设计流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="structure_grade",
            label="建筑物等级",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="build_date",
            label="建成年月",
            input_type="month",
            required=True,
        ),
        FieldDefinition(
            key="renovation_date",
            label="加固改造年月",
            input_type="month",
            required=False,
            placeholder=("例如：202109，可留空"),
        ),
        FieldDefinition(
            key="length",
            label="长度",
            input_type="decimal",
            required=True,
        ),
        FieldDefinition(
            key="increased_flow",
            label="加大流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        # -----------------------------------------------------
        # 三、结构参数
        # -----------------------------------------------------
        FieldDefinition(
            key="structure_form",
            label="结构形式",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="section_size",
            label="尺寸",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="pipe_body_structure",
            label="管身结构",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="wall_thickness",
            label="壁厚度",
            input_type="decimal",
            required=True,
        ),
        FieldDefinition(
            key="waterstop_form",
            label="止水形式",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="channel_bottom_elevation",
            label="渠底高程",
            input_type="signed_decimal",
            required=True,
        ),
    ),
    sections=(
        FormSectionDefinition(
            title="二、工程基本信息",
            rows=(
                FieldRowDefinition(("asset_name",)),
                FieldRowDefinition(("stake",)),
                FieldRowDefinition(("design_flow",)),
                FieldRowDefinition(("structure_grade",)),
                FieldRowDefinition(("build_date",)),
                FieldRowDefinition(("renovation_date",)),
                FieldRowDefinition(("length",)),
                FieldRowDefinition(("increased_flow",)),
            ),
        ),
        FormSectionDefinition(
            title="三、结构参数",
            rows=(
                FieldRowDefinition(("structure_form",)),
                FieldRowDefinition(("section_size",)),
                FieldRowDefinition(("pipe_body_structure",)),
                FieldRowDefinition(("wall_thickness",)),
                FieldRowDefinition(("waterstop_form",)),
                FieldRowDefinition(("channel_bottom_elevation",)),
            ),
        ),
    ),
    # =========================================================
    # 当前批次列表
    # =========================================================
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text='新增倒虹吸调查',
        )
    ),
    evaluation_items=tuple(INVERTED_SIPHON_EVALUATION_ITEMS),
    grade_options=(
        "A",
        "B",
        "C",
        "D",
    ),
    evaluation_title=("四、分项评价"),
    conclusion_title=("五、调查结论"),
)
