from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.extension_models import (
    OriginalFormCellBinding,
    OriginalFormConclusionBinding,
    OriginalFormEvaluationBinding,
    OriginalFormExportDefinition,
    OriginalFormPrintSettings,
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.masonry_evaluation import (
    MASONRY_EVALUATION_ITEMS,
)


FORM_2_13 = EngineeringFormDefinition(
    form_code="form_2_13",
    form_number="2.13",
    form_name="砌石工程状况调查表",
    asset_type="masonry_structure",
    business_type_code="13",
    asset_name_field="asset_name",
    position=PositionDefinition.point(
        stake_field="stake",
        stake_value_key="stake_value",
    ),
    fields=(
        FieldDefinition(
            key="asset_name",
            label="名称",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="stake",
            label="桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="design_flow",
            label="设计流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="longitudinal_slope",
            label="纵比降",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="structure_grade",
            label="建筑物等级",
            input_type="structure_grade",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="build_date",
            label="建成年月",
            input_type="month",
            required=True,
            placeholder="例如：201006",
        ),
        FieldDefinition(
            key="renovation_date",
            label="加固改造年月",
            input_type="month",
            required=False,
            placeholder="例如：202109，可留空",
        ),
        FieldDefinition(
            key="increased_flow",
            label="加大流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="channel_bottom_elevation",
            label="渠底高程",
            input_type="signed_decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="length",
            label="长度",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="bottom_width",
            label="渠底宽度",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="channel_depth",
            label="渠深",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="top_width",
            label="渠口宽",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="lining_thickness",
            label="衬砌厚度",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="section_form",
            label="断面形式",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="bed_soil",
            label="渠床土质",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="earthwork_type",
            label="挖/填方渠道",
            input_type="choice",
            required=True,
            choices=('挖方', '填方'),
        ),
        FieldDefinition(
            key="water_conveyance_loss",
            label="输水损失",
            input_type="decimal",
            required=True,
            unit="m³/km",
        ),
    ),
    sections=(
        FormSectionDefinition(
            title="二、工程基本信息",
            rows=(
                FieldRowDefinition(('asset_name',)),
                FieldRowDefinition(('stake',)),
                FieldRowDefinition(('design_flow',)),
                FieldRowDefinition(('longitudinal_slope',)),
                FieldRowDefinition(('structure_grade',)),
                FieldRowDefinition(('build_date',)),
                FieldRowDefinition(('renovation_date',)),
                FieldRowDefinition(('increased_flow',)),
            ),
        ),
        FormSectionDefinition(
            title="三、渠体参数",
            rows=(
                FieldRowDefinition(('channel_bottom_elevation',)),
                FieldRowDefinition(('length',)),
                FieldRowDefinition(('bottom_width',)),
                FieldRowDefinition(('channel_depth',)),
                FieldRowDefinition(('top_width',)),
                FieldRowDefinition(('lining_thickness',)),
                FieldRowDefinition(('section_form',)),
                FieldRowDefinition(('bed_soil',)),
                FieldRowDefinition(('earthwork_type',)),
                FieldRowDefinition(('water_conveyance_loss',)),
            ),
        ),
    ),
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text="新增砌石工程调查",
        )
    ),
    # =========================================================
    # 详细汇总导出
    # =========================================================
    summary_export_definition=SummaryExportDefinition(
        sheet_name='砌石工程调查汇总',
        columns=(
            SummaryColumnDefinition(
                header='业务编号',
                width=22,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='business_code',
                ),
            ),
            SummaryColumnDefinition(
                header='名称',
                width=20,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            SummaryColumnDefinition(
                header='基层处',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='department_name',
                ),
            ),
            SummaryColumnDefinition(
                header='水管所',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='office_name',
                ),
            ),
            SummaryColumnDefinition(
                header='渠系',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='canal_name',
                ),
            ),
            SummaryColumnDefinition(
                header='桩号',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stake',
                ),
            ),
            SummaryColumnDefinition(
                header='设计流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='纵比降',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='longitudinal_slope',
                ),
            ),
            SummaryColumnDefinition(
                header='建筑物等级',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            SummaryColumnDefinition(
                header='建成年月',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            SummaryColumnDefinition(
                header='加固改造年月',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            SummaryColumnDefinition(
                header='加大流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='increased_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='渠底高程（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='channel_bottom_elevation',
                ),
            ),
            SummaryColumnDefinition(
                header='长度',
                width=12,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='length',
                ),
            ),
            SummaryColumnDefinition(
                header='渠底宽度（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='bottom_width',
                ),
            ),
            SummaryColumnDefinition(
                header='渠深（m）',
                width=12,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='channel_depth',
                ),
            ),
            SummaryColumnDefinition(
                header='渠口宽（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='top_width',
                ),
            ),
            SummaryColumnDefinition(
                header='衬砌厚度（m）',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='lining_thickness',
                ),
            ),
            SummaryColumnDefinition(
                header='断面形式',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='section_form',
                ),
            ),
            SummaryColumnDefinition(
                header='渠床土质',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='bed_soil',
                ),
            ),
            SummaryColumnDefinition(
                header='挖/填方渠道',
                width=14,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='earthwork_type',
                ),
            ),
            SummaryColumnDefinition(
                header='输水损失（m³/km）',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='water_conveyance_loss',
                ),
            ),
        ),
    ),
    # =========================================================
    # 正式原表导出
    # =========================================================
    original_form_export_definition=OriginalFormExportDefinition(
        template_filename='form_2_13_V1.xlsx',
        sheet_name='附表2.13',
        field_bindings=(
            OriginalFormCellBinding(
                cell='B5',
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            OriginalFormCellBinding(
                cell='H5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stake',
                ),
            ),
            OriginalFormCellBinding(
                cell='J5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='longitudinal_slope',
                ),
            ),
            OriginalFormCellBinding(
                cell='D6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            OriginalFormCellBinding(
                cell='F6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='H6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='J6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='increased_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='channel_bottom_elevation',
                ),
            ),
            OriginalFormCellBinding(
                cell='D7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='length',
                ),
            ),
            OriginalFormCellBinding(
                cell='F7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='bottom_width',
                ),
            ),
            OriginalFormCellBinding(
                cell='H7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='channel_depth',
                ),
            ),
            OriginalFormCellBinding(
                cell='J7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='top_width',
                ),
            ),
            OriginalFormCellBinding(
                cell='B8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='lining_thickness',
                ),
            ),
            OriginalFormCellBinding(
                cell='D8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='section_form',
                ),
            ),
            OriginalFormCellBinding(
                cell='F8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='bed_soil',
                ),
            ),
            OriginalFormCellBinding(
                cell='H8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='earthwork_type',
                ),
            ),
            OriginalFormCellBinding(
                cell='J8',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='water_conveyance_loss',
                ),
            ),
        ),
        evaluation_binding=OriginalFormEvaluationBinding(
            column="E",
            start_row=10,
        ),
        conclusion_binding=OriginalFormConclusionBinding(
            survey_comment_cell='C14',
            overall_grade_cell='J14',
            survey_date_cell='J15',
        ),
        print_settings=OriginalFormPrintSettings(
            print_area='A1:J16',
        ),
        output_filename_prefix='附表2.13_砌石工程状况调查表',
        fallback_asset_name='砌石工程',
    ),
    evaluation_items=tuple(
        MASONRY_EVALUATION_ITEMS
    ),
    grade_options=(
        "A",
        "B",
        "C",
        "D",
    ),
    evaluation_title="四、分项评价",
    conclusion_title="五、调查结论",
)
