from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.extension_models import (
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.sluice_gate_evaluation import (
    SLUICE_GATE_EVALUATION_ITEMS,
)

FORM_2_2 = EngineeringFormDefinition(
    form_code="form_2_2",
    form_number="2.2",
    form_name=("水闸工程状况调查表"),
    asset_type="sluice_gate",
    business_type_code="02",
    asset_name_field="asset_name",
    position=PositionDefinition.point(
        stake_field="stake",
        stake_value_key="stake_value",
    ),
    fields=(
        # -----------------------------------------------------
        # 二、工程基本信息
        # -----------------------------------------------------
        FieldDefinition(
            key="asset_name",
            label="工程名称",
            input_type="text",
            required=True,
            placeholder="例如：1号节制闸",
        ),
        FieldDefinition(
            key="stake",
            label="桩号",
            input_type="stake",
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key="design_flow",
            label="设计流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        FieldDefinition(
            key="structure_grade",
            label="建筑物等级",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="build_date",
            label="建成年月",
            input_type="month",
            required=True,
        ),
        FieldDefinition(
            key="renovation_date",
            label="加固改造年月",
            input_type="month",
            required=False,
            placeholder=("例如：202109，可留空"),
        ),
        FieldDefinition(
            key="increased_flow",
            label="加大流量",
            input_type="decimal",
            required=True,
            unit="m³/s",
        ),
        # -----------------------------------------------------
        # 三、结构与材料参数
        # -----------------------------------------------------
        FieldDefinition(
            key="opening_count",
            label="孔数",
            input_type="integer",
            required=True,
            maximum=999999,
        ),
        FieldDefinition(
            key="opening_width",
            label="孔宽",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="opening_height",
            label="孔高",
            input_type="decimal",
            required=True,
            unit="m",
        ),
        FieldDefinition(
            key="main_component_material",
            label="主要构件材料",
            input_type="text",
            required=True,
            placeholder="例如：钢筋混凝土",
        ),
        FieldDefinition(
            key="concrete_strength",
            label="混凝土强度",
            input_type="text",
            required=True,
            placeholder="例如：C30",
        ),
        FieldDefinition(
            key=("reinforced_concrete_strength"),
            label="钢筋混凝土强度",
            input_type="text",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key="cover_thickness",
            label="保护层厚度",
            input_type="decimal",
            required=True,
            unit="mm",
        ),
        FieldDefinition(
            key="crack_width_limit",
            label="裂缝限宽",
            input_type="decimal",
            required=True,
            unit="mm",
        ),
    ),
    sections=(
        FormSectionDefinition(
            title="二、工程基本信息",
            rows=(
                FieldRowDefinition(("asset_name",)),
                FieldRowDefinition(("stake",)),
                FieldRowDefinition(("design_flow",)),
                FieldRowDefinition(("structure_grade",)),
                FieldRowDefinition(("build_date",)),
                FieldRowDefinition(("renovation_date",)),
                FieldRowDefinition(("increased_flow",)),
            ),
        ),
        FormSectionDefinition(
            title=("三、结构与材料参数"),
            rows=(
                FieldRowDefinition(("opening_count",)),
                FieldRowDefinition(("opening_width",)),
                FieldRowDefinition(("opening_height",)),
                FieldRowDefinition(("main_component_material",)),
                FieldRowDefinition(("concrete_strength",)),
                FieldRowDefinition(("reinforced_concrete_strength",)),
                FieldRowDefinition(("cover_thickness",)),
                FieldRowDefinition(("crack_width_limit",)),
            ),
        ),
    ),
    # =========================================================
    # 当前批次列表
    # =========================================================
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text='新增水闸调查',
        )
    ),
    # =========================================================
    # 详细汇总导出
    # =========================================================
    summary_export_definition=SummaryExportDefinition(
        sheet_name="水闸调查汇总",
        columns=(
            SummaryColumnDefinition(
                header="业务编号",
                width=22,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="business_code",
                ),
            ),
            SummaryColumnDefinition(
                header="工程名称",
                width=20,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="asset_name",
                ),
            ),
            SummaryColumnDefinition(
                header="基层处",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="department_name",
                ),
            ),
            SummaryColumnDefinition(
                header="水管所",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="office_name",
                ),
            ),
            SummaryColumnDefinition(
                header="渠系",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="canal_name",
                ),
            ),
            SummaryColumnDefinition(
                header="桩号",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="stake",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="设计流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="design_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建筑物等级",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_grade",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建成年月",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="build_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加固改造年月",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="renovation_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加大流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="increased_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="孔数",
                width=10,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="opening_count",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="孔宽",
                width=10,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="opening_width",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="孔高",
                width=10,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="opening_height",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="主要构件材料",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="main_component_material",
                ),
            ),
            SummaryColumnDefinition(
                header="混凝土强度",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="concrete_strength",
                ),
            ),
            SummaryColumnDefinition(
                header="钢筋混凝土强度",
                width=20,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="reinforced_concrete_strength",
                ),
            ),
            SummaryColumnDefinition(
                header="保护层厚度",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="cover_thickness",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="裂缝限宽",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="crack_width_limit",
                ),
                alignment="center",
            ),
        ),
    ),
    evaluation_items=tuple(SLUICE_GATE_EVALUATION_ITEMS),
    grade_options=(
        "A",
        "B",
        "C",
        "D",
    ),
    evaluation_title=("四、分项评价"),
    conclusion_title=("五、调查结论"),
)
