from forms.engineering.models import (
    EngineeringFormDefinition,
    FieldDefinition,
    FieldRowDefinition,
    FormSectionDefinition,
    PositionDefinition,
)

from forms.engineering.extension_models import (
    OriginalFormCellBinding,
    OriginalFormConclusionBinding,
    OriginalFormEvaluationBinding,
    OriginalFormExportDefinition,
    OriginalFormPrintSettings,
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

from services.weir_flume_measurement_evaluation import (
    WEIR_FLUME_MEASUREMENT_EVALUATION_ITEMS,
)


FORM_2_11 = EngineeringFormDefinition(
    form_code="form_2_11",
    form_number="2.11",
    form_name='堰槽量水（巴歇尔/无喉道量水堰）量水设施工程状况调查表',
    asset_type='weir_flume_measurement_facility',
    business_type_code='11',
    asset_name_field="asset_name",
    position=PositionDefinition.point(
        stake_field="stake",
        stake_value_key="stake_value",
    ),
    fields=(
        FieldDefinition(
            key='asset_name',
            label='名称',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='stake',
            label='桩号',
            input_type='stake',
            required=True,
            placeholder="例如：CH12+350",
        ),
        FieldDefinition(
            key='design_flow',
            label='设计流量',
            input_type='decimal',
            required=True,
            unit='m³/s',
        ),
        FieldDefinition(
            key='structure_grade',
            label='建筑物等级',
            input_type="structure_grade",
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='build_date',
            label='建成年月',
            input_type='month',
            required=True,
            placeholder="例如：201006",
        ),
        FieldDefinition(
            key='renovation_date',
            label='加固改造年月',
            input_type='month',
            required=False,
            placeholder="例如：202109，可留空",
        ),
        FieldDefinition(
            key='length',
            label='长度',
            input_type='decimal',
            required=True,
            unit='m',
        ),
        FieldDefinition(
            key='increased_flow',
            label='加大流量',
            input_type='decimal',
            required=True,
            unit='m³/s',
        ),
        FieldDefinition(
            key='measurement_weir_type',
            label='量水堰类型',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='main_structure_material',
            label='主构建筑材料',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
        FieldDefinition(
            key='flume_type',
            label='槽型（W×L）',
            input_type='text',
            required=True,
            placeholder="按原始资料填写",
        ),
    ),
    sections=(
        FormSectionDefinition(
            title='二、工程基本信息',
            rows=(
                FieldRowDefinition(('asset_name',)),
                FieldRowDefinition(('stake',)),
                FieldRowDefinition(('design_flow',)),
                FieldRowDefinition(('structure_grade',)),
                FieldRowDefinition(('build_date',)),
                FieldRowDefinition(('renovation_date',)),
                FieldRowDefinition(('length',)),
                FieldRowDefinition(('increased_flow',)),
            ),
        ),
        FormSectionDefinition(
            title='三、量水设施参数',
            rows=(
                FieldRowDefinition(('measurement_weir_type',)),
                FieldRowDefinition(('main_structure_material',)),
                FieldRowDefinition(('flume_type',)),
            ),
        ),
    ),
    list_definition=(
        build_standard_engineering_list_definition(
            new_button_text='新增堰槽量水设施调查',
        )
    ),
    # =========================================================
    # 详细汇总导出
    # =========================================================
    summary_export_definition=SummaryExportDefinition(
        sheet_name='堰槽量水设施调查汇总',
        columns=(
            SummaryColumnDefinition(
                header='业务编号',
                width=22,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='business_code',
                ),
            ),
            SummaryColumnDefinition(
                header='名称',
                width=20,
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            SummaryColumnDefinition(
                header='基层处',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='department_name',
                ),
            ),
            SummaryColumnDefinition(
                header='水管所',
                width=16,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='office_name',
                ),
            ),
            SummaryColumnDefinition(
                header='渠系',
                width=18,
                binding=ValueBindingDefinition.single(
                    source='query_record',
                    key='canal_name',
                ),
            ),
            SummaryColumnDefinition(
                header='桩号',
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='stake',
                ),
            ),
            SummaryColumnDefinition(
                header='设计流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='design_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='建筑物等级',
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='structure_grade',
                ),
            ),
            SummaryColumnDefinition(
                header='建成年月',
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='build_date',
                ),
            ),
            SummaryColumnDefinition(
                header='加固改造年月',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='renovation_date',
                ),
            ),
            SummaryColumnDefinition(
                header='长度（m）',
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='length',
                ),
            ),
            SummaryColumnDefinition(
                header='加大流量（m³/s）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='increased_flow',
                ),
            ),
            SummaryColumnDefinition(
                header='量水堰类型',
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='measurement_weir_type',
                ),
            ),
            SummaryColumnDefinition(
                header='主构建筑材料',
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='main_structure_material',
                ),
            ),
            SummaryColumnDefinition(
                header='槽型（W×L）',
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key='flume_type',
                ),
            ),
        ),
    ),
    # =========================================================
    # 正式原表导出
    # =========================================================
    original_form_export_definition=OriginalFormExportDefinition(
        template_filename='form_2_11_V1.xlsx',
        sheet_name='附表2.11',
        field_bindings=(
            OriginalFormCellBinding(
                cell='B5',
                binding=ValueBindingDefinition.single(
                    source='record',
                    key='asset_name',
                ),
            ),
            OriginalFormCellBinding(
                cell='H5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='stake',
                ),
            ),
            OriginalFormCellBinding(
                cell='J5',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='design_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='structure_grade',
                ),
            ),
            OriginalFormCellBinding(
                cell='D6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='build_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='F6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='renovation_date',
                ),
            ),
            OriginalFormCellBinding(
                cell='H6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='length',
                ),
            ),
            OriginalFormCellBinding(
                cell='J6',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='increased_flow',
                ),
            ),
            OriginalFormCellBinding(
                cell='B7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='measurement_weir_type',
                ),
            ),
            OriginalFormCellBinding(
                cell='D7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='main_structure_material',
                ),
            ),
            OriginalFormCellBinding(
                cell='F7',
                binding=ValueBindingDefinition.single(
                    source='record_data',
                    key='flume_type',
                ),
            ),
        ),
        evaluation_binding=OriginalFormEvaluationBinding(
            column="E",
            start_row=9,
        ),
        conclusion_binding=OriginalFormConclusionBinding(
            survey_comment_cell='C20',
            overall_grade_cell='J20',
            survey_date_cell='J21',
        ),
        print_settings=OriginalFormPrintSettings(
            print_area='A1:J22',
        ),
        output_filename_prefix='附表2.11_堰槽量水设施工程状况调查表',
        fallback_asset_name='堰槽量水设施',
    ),
    evaluation_items=tuple(
        WEIR_FLUME_MEASUREMENT_EVALUATION_ITEMS
    ),
    grade_options=(
        "A",
        "B",
        "C",
    ),
    evaluation_title="四、分项评价",
    conclusion_title="五、调查结论",
)
