from dataclasses import fields

from forms.engineering.models import EngineeringFormDefinition

from shared.forms.engineering.form_2_4 import FORM_2_4 as CORE_DEFINITION

from forms.engineering.extension_models import (
    SummaryColumnDefinition,
    SummaryExportDefinition,
    ValueBindingDefinition,
)

from forms.engineering.formatters import (
    format_stake_range_compact,
)

from forms.engineering.list_definitions import (
    build_standard_engineering_list_definition,
)

FORM_2_4 = EngineeringFormDefinition(
    **{field.name: getattr(CORE_DEFINITION, field.name) for field in fields(CORE_DEFINITION)},
    list_definition=build_standard_engineering_list_definition(
            new_button_text='新增倒虹吸调查',
        ),
    summary_export_definition=SummaryExportDefinition(
        sheet_name="倒虹吸调查汇总",
        columns=(
            SummaryColumnDefinition(
                header="业务编号",
                width=22,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="business_code",
                ),
            ),
            SummaryColumnDefinition(
                header="名称",
                width=20,
                binding=ValueBindingDefinition.single(
                    source="record",
                    key="asset_name",
                ),
            ),
            SummaryColumnDefinition(
                header="基层处",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="department_name",
                ),
            ),
            SummaryColumnDefinition(
                header="水管所",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="office_name",
                ),
            ),
            SummaryColumnDefinition(
                header="渠系",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="query_record",
                    key="canal_name",
                ),
            ),
            SummaryColumnDefinition(
                header="桩号",
                width=14,
                binding=ValueBindingDefinition.composite(
                            source="record_data",
                            keys=("start_stake", "end_stake"),
                            formatter=format_stake_range_compact,
                        ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="设计流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="design_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建筑物等级",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_grade",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="建成年月",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="build_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加固改造年月",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="renovation_date",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="长度",
                width=12,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="length",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="加大流量（m³/s）",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="increased_flow",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="结构形式",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="structure_form",
                ),
            ),
            SummaryColumnDefinition(
                header="尺寸",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="section_size",
                ),
            ),
            SummaryColumnDefinition(
                header="管身结构",
                width=18,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="pipe_body_structure",
                ),
            ),
            SummaryColumnDefinition(
                header="壁厚度",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="wall_thickness",
                ),
                alignment="center",
            ),
            SummaryColumnDefinition(
                header="止水形式",
                width=16,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="waterstop_form",
                ),
            ),
            SummaryColumnDefinition(
                header="渠底高程",
                width=14,
                binding=ValueBindingDefinition.single(
                    source="record_data",
                    key="channel_bottom_elevation",
                ),
                alignment="center",
            ),
        ),
    ),
)
